import { Animal, InventoryItem, Transaction, DashboardStats } from './types';

export const mockAnimals: Animal[] = [
    {
        id: '1',
        user_id: 'user-1',
        tag_number: 'TR-001',
        name: 'Bella',
        species: 'Cow',
        breed: 'Holstein',
        gender: 'Female',
        birth_date: '2021-01-15',
        weight: 650,
        purchase_price: 5000,
        purchase_date: '2023-01-15',
        photo_url: null,
        status: 'Healthy',
        sold_price: null,
        sold_date: null,
        notes: null,
        created_at: '2023-01-15T10:00:00Z',
    },
    {
        id: '2',
        user_id: 'user-1',
        tag_number: 'TR-002',
        name: 'Daisy',
        species: 'Cow',
        breed: 'Jersey',
        gender: 'Female',
        birth_date: '2021-05-20',
        weight: 450,
        purchase_price: 4500,
        purchase_date: '2023-05-20',
        photo_url: null,
        status: 'Pregnant',
        sold_price: null,
        sold_date: null,
        notes: null,
        created_at: '2023-05-20T10:00:00Z',
    },
    {
        id: '3',
        user_id: 'user-1',
        tag_number: 'TR-003',
        name: 'Luna',
        species: 'Sheep',
        breed: 'Merino',
        gender: 'Female',
        birth_date: '2022-08-10',
        weight: 60,
        purchase_price: 1500,
        purchase_date: '2023-08-10',
        photo_url: null,
        status: 'Sick',
        sold_price: null,
        sold_date: null,
        notes: 'Respiratory infection',
        created_at: '2023-08-10T10:00:00Z',
    },
    {
        id: '4',
        user_id: 'user-1',
        tag_number: 'TR-004',
        name: 'Max',
        species: 'Goat',
        breed: 'Boer',
        gender: 'Male',
        birth_date: '2022-06-01',
        weight: 75,
        purchase_price: 1200,
        purchase_date: '2023-06-01',
        photo_url: null,
        status: 'Healthy',
        sold_price: null,
        sold_date: null,
        notes: null,
        created_at: '2023-06-01T10:00:00Z',
    },
    {
        id: '5',
        user_id: 'user-1',
        tag_number: 'TR-005',
        name: 'Star',
        species: 'Cow',
        breed: 'Angus',
        gender: 'Female',
        birth_date: '2020-11-05',
        weight: 700,
        purchase_price: 6000,
        purchase_date: '2022-11-05',
        photo_url: null,
        status: 'Healthy',
        sold_price: null,
        sold_date: null,
        notes: null,
        created_at: '2022-11-05T10:00:00Z',
    },
];

export const mockInventory: InventoryItem[] = [
    {
        id: '1',
        name: 'Cattle Feed Premium',
        type: 'Feed',
        quantity: 1500,
        unit: 'kg',
        minLevel: 500,
        pricePerUnit: 12.5,
        lastUpdated: '2023-11-15',
    },
    {
        id: '2',
        name: 'Antibiotics A',
        type: 'Medicine',
        quantity: 5,
        unit: 'units',
        minLevel: 10,
        pricePerUnit: 150,
        lastUpdated: '2023-10-20',
    },
    {
        id: '3',
        name: 'Hay Bales',
        type: 'Feed',
        quantity: 45,
        unit: 'units',
        minLevel: 50,
        pricePerUnit: 80,
        lastUpdated: '2023-11-18',
    },
    {
        id: '4',
        name: 'Milking Machine Parts',
        type: 'Equipment',
        quantity: 2,
        unit: 'units',
        minLevel: 1,
        pricePerUnit: 2500,
        lastUpdated: '2023-09-01',
    },
];

export const mockTransactions: Transaction[] = [
    {
        id: '1',
        date: '2023-11-01',
        description: 'Sold 500L Milk',
        amount: 7500,
        type: 'Income',
        category: 'Sales',
    },
    {
        id: '2',
        date: '2023-11-03',
        description: 'Purchased Cattle Feed',
        amount: 3000,
        type: 'Expense',
        category: 'Feed',
    },
    {
        id: '3',
        date: '2023-11-05',
        description: 'Vet Visit',
        amount: 500,
        type: 'Expense',
        category: 'Medicine',
    },
    {
        id: '4',
        date: '2023-11-10',
        description: 'Sold 2 Calves',
        amount: 12000,
        type: 'Income',
        category: 'Sales',
    },
    {
        id: '5',
        date: '2023-11-15',
        description: 'Electricity Bill',
        amount: 1200,
        type: 'Expense',
        category: 'Other',
    },
];

export const mockStats: DashboardStats = {
    totalAnimals: 45,
    sickAnimals: 2,
    lowStockItems: 3,
    monthlyIncome: 25000,
    monthlyExpense: 8500,
};
